services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Quellenform\ContentVisibility\:
    resource: '../Classes/*'

  Quellenform\ContentVisibility\DataProcessing\VisibilityProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'ContentVisibility'
