services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Quellenform\ContentVisibility\:
    resource: '../Classes/*'

  Quellenform\ContentVisibility\DataProcessing\VisibilityProcessor:
    shared: false
    public: false
    tags:
      - { name: 'data.processor', identifier: 'content-visibility' }
